version: '3.8' 

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - UI_BASE_URL=$UI_BASE_URL
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - API_BASE_URL=$API_BASE_URL
    ports:
      - "80:80"
    restart: unless-stopped
